export const JOB_TITLES = [
  "WordPress Designer",
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "UI/UX Designer",
  "Mobile App Developer",
  "Shopify Developer",
  "Web Scraping Specialist",
  "DevOps Engineer",
  "AI/ML Developer",
  "Blockchain Developer",
  "Content Writer",
  "SEO Specialist",
  "Social Media Manager",
  "Data Analyst",
  "Game Developer",
];

// WordPress Designer Skills - Expanded
export const WORDPRESS_DESIGNER_SKILLS = [
  "WordPress Theme Development",
  "PHP",
  "UI/UX Design",
  "Elementor",
  "Divi",
  "Beaver Builder",
  "WooCommerce",
  "WordPress Security",
  "Custom Post Types",
  "WordPress Multisite",
  "CSS/SCSS",
  "WordPress Performance Optimization",
  "Gutenberg Block Editor",
  "Web Accessibility",
  "WordPress Template Hierarchy",
  "Responsive Design",
  "ACF (Advanced Custom Fields)",
  "Yoast SEO",
  "WordPress Migration",
  "WordPress Hosting Management",
  "Genesis Framework",
  "WordPress REST API",
  "WordPress Child Themes",
  "JavaScript/jQuery for WordPress",
  "Plugin Development",
];

// Frontend Developer Skills - Expanded
export const FRONTEND_DEVELOPER_SKILLS = [
  "HTML5",
  "CSS3",
  "JavaScript",
  "React",
  "Vue.js",
  "Angular",
  "TypeScript",
  "SASS/LESS",
  "Webpack",
  "Vite",
  "Jest",
  "Cypress",
  "Redux",
  "Zustand",
  "Flexbox/Grid",
  "REST API Integration",
  "GraphQL",
  "Responsive Web Design",
  "Progressive Web Apps (PWA)",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Web Accessibility (WCAG)",
  "Cross-Browser Compatibility",
  "Animation (GSAP, Framer Motion)",
  "Performance Optimization",
  "Storybook",
  "Svelte",
  "SolidJS",
  "Web Components",
];

// Back-end Developer Skills - Expanded
export const BACKEND_DEVELOPER_SKILLS = [
  "Node.js",
  "Python",
  "PHP",
  "Java",
  "C#",
  "SQL",
  "MongoDB",
  "RESTful API Development",
  "OAuth/JWT",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "RabbitMQ",
  "Kafka",
  "Redis",
  "Express.js",
  "Django",
  "Flask",
  "Laravel",
  "Spring Boot",
  "ASP.NET Core",
  "GraphQL API Development",
  "Microservices Architecture",
  "Database Design & Optimization",
  "Serverless Functions",
  "Message Queues",
  "API Documentation",
  "Websockets",
  "gRPC",
  "Elasticsearch",
  "Caching Strategies",
];

// Fullstack Developer Skills - Expanded
export const FULLSTACK_DEVELOPER_SKILLS = [
  "Express.js",
  "Django",
  "Laravel",
  "Spring Boot",
  ".NET Core",
  "PostgreSQL",
  "MySQL",
  "Firebase",
  "Jenkins",
  "GitHub Actions",
  "CircleCI",
  "Heroku",
  "Netlify",
  "Vercel",
  "Next.js",
  "Nuxt.js",
  "Serverless Framework",
  "Socket.io",
  "Postman",
  "Swagger",
  "CI/CD Pipelines",
  "TDD (Test Driven Development)",
  "MERN Stack",
  "MEAN Stack",
  "LAMP Stack",
  "JAMstack",
  "T3 Stack",
  "Prisma",
  "tRPC",
  "Full-Stack Testing",
  "System Architecture Design",
  "Database Migrations",
  "Authentication Systems",
  "Payment Gateway Integration",
  "Third-party API Integration",
];

// UI/UX Designer Skills
export const UI_UX_DESIGNER_SKILLS = [
  "Figma",
  "Adobe XD",
  "Sketch",
  "InVision",
  "Prototyping",
  "Wireframing",
  "User Research",
  "User Testing",
  "Interaction Design",
  "Visual Design",
  "Information Architecture",
  "Design Systems",
  "Typography",
  "Color Theory",
  "Responsive Design",
  "Mobile-First Design",
  "Accessibility Design",
  "UI Animation",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Usability Testing",
  "User Personas",
  "User Flows",
  "Material Design",
  "Human Interface Guidelines",
];

// Mobile App Developer Skills
export const MOBILE_APP_DEVELOPER_SKILLS = [
  "React Native",
  "Flutter",
  "Swift",
  "Kotlin",
  "Java for Android",
  "SwiftUI",
  "Jetpack Compose",
  "Firebase",
  "RESTful API Integration",
  "GraphQL",
  "Mobile UI/UX Design",
  "App Store Optimization",
  "Mobile Analytics",
  "Push Notifications",
  "Offline Storage",
  "App Publishing",
  "App Performance Optimization",
  "Mobile Authentication",
  "In-App Purchases",
  "Responsive Layouts",
  "Cross-Platform Development",
  "Native Module Integration",
  "WebView Integration",
  "Deep Linking",
  "Mobile Testing",
];

// Shopify Developer Skills
export const SHOPIFY_DEVELOPER_SKILLS = [
  "Shopify Theme Development",
  "Liquid Template Language",
  "Shopify API",
  "Shopify App Development",
  "Shopify Plus",
  "E-commerce UI/UX",
  "JavaScript/jQuery",
  "Responsive Design",
  "CSS/SCSS",
  "Shopify Checkout Customization",
  "Payment Gateway Integration",
  "Shipping Integration",
  "Third-party App Integration",
  "Theme Customization",
  "Product Page Optimization",
  "Shopify Polaris",
  "Shopify CLI",
  "Theme Kit",
  "Slate",
  "Shopify Metafields",
  "Custom Shopify Sections",
  "Performance Optimization",
  "SEO for Shopify",
  "Shopify Store Migration",
  "Headless Shopify",
];

// Web Scraping Specialist Skills
export const WEB_SCRAPING_SPECIALIST_SKILLS = [
  "Python",
  "Beautiful Soup",
  "Selenium",
  "Scrapy",
  "Puppeteer",
  "HTTP Requests",
  "API Integration",
  "Data Parsing",
  "Data Cleaning",
  "XPath",
  "CSS Selectors",
  "JavaScript DOM Manipulation",
  "Proxy Management",
  "CAPTCHA Solving",
  "Rate Limiting",
  "Data Storage (SQL/NoSQL)",
  "Data Transformation",
  "Regular Expressions",
  "Web Structure Analysis",
  "Anti-Bot Detection Bypassing",
  "Headless Browsers",
  "Data Extraction Automation",
  "Error Handling",
  "Scraping Ethics",
  "Legal Compliance",
];

// DevOps Engineer Skills
export const DEVOPS_ENGINEER_SKILLS = [
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitHub Actions",
  "CircleCI",
  "Travis CI",
  "CI/CD Pipelines",
  "Infrastructure as Code",
  "Linux Administration",
  "Shell Scripting",
  "Monitoring Tools (Prometheus, Grafana)",
  "Logging (ELK Stack)",
  "Networking",
  "Security Best Practices",
  "Containerization",
  "Microservices Architecture",
  "Cloud Cost Optimization",
  "Disaster Recovery",
  "High Availability Design",
  "Performance Tuning",
];

// AI/ML Developer Skills
export const AI_ML_DEVELOPER_SKILLS = [
  "Python",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Data Preprocessing",
  "Data Visualization",
  "Machine Learning Algorithms",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Recommender Systems",
  "Feature Engineering",
  "Model Deployment",
  "Model Optimization",
  "A/B Testing",
  "Time Series Analysis",
  "Reinforcement Learning",
  "Neural Networks",
  "Data Mining",
  "Statistical Analysis",
  "Jupyter Notebooks",
  "Pandas",
  "NumPy",
  "Hugging Face",
  "MLOps",
];

// Blockchain Developer Skills
export const BLOCKCHAIN_DEVELOPER_SKILLS = [
  "Solidity",
  "Smart Contract Development",
  "Ethereum",
  "Web3.js",
  "Ethers.js",
  "Truffle",
  "Hardhat",
  "Remix IDE",
  "MetaMask Integration",
  "ERC Standards (ERC-20, ERC-721)",
  "DApp Development",
  "Blockchain Architecture",
  "Consensus Mechanisms",
  "Cryptography",
  "Gas Optimization",
  "Security Auditing",
  "IPFS",
  "Tokenomics",
  "NFT Development",
  "Cross-Chain Development",
  "Layer 2 Solutions",
  "Solana Development",
  "Binance Smart Chain",
  "Polygon",
  "Blockchain Testing",
];

// Content Writer Skills
export const CONTENT_WRITER_SKILLS = [
  "Blog Writing",
  "SEO Writing",
  "Technical Writing",
  "Copywriting",
  "Content Strategy",
  "Content Editing",
  "Proofreading",
  "Research Skills",
  "Keyword Research",
  "Content Optimization",
  "Storytelling",
  "Brand Voice Development",
  "Social Media Copy",
  "Email Marketing Copy",
  "Landing Page Copy",
  "White Papers",
  "Case Studies",
  "Product Descriptions",
  "Press Releases",
  "Script Writing",
  "Content Analytics",
  "Markdown",
  "CMS (WordPress, etc.)",
  "Content Calendars",
  "Style Guides",
];

// SEO Specialist Skills
export const SEO_SPECIALIST_SKILLS = [
  "Keyword Research",
  "On-Page SEO",
  "Off-Page SEO",
  "Technical SEO",
  "Link Building",
  "SEO Auditing",
  "Google Analytics",
  "Google Search Console",
  "SEO Tools (SEMrush, Ahrefs, Moz)",
  "Competitor Analysis",
  "Content Optimization",
  "Schema Markup",
  "Local SEO",
  "Mobile SEO",
  "Voice Search Optimization",
  "E-commerce SEO",
  "International SEO",
  "Page Speed Optimization",
  "SEO Reporting",
  "Google Algorithm Updates",
  "SEO Strategy",
  "User Intent Analysis",
  "Backlink Analysis",
  "SEO Copywriting",
  "Conversion Rate Optimization",
];

// Social Media Manager Skills
export const SOCIAL_MEDIA_MANAGER_SKILLS = [
  "Social Media Strategy",
  "Content Creation",
  "Content Scheduling",
  "Community Management",
  "Social Media Analytics",
  "Facebook Ads",
  "Instagram Marketing",
  "Twitter Marketing",
  "LinkedIn Marketing",
  "TikTok Marketing",
  "Pinterest Marketing",
  "Social Media Design",
  "Hashtag Strategy",
  "Influencer Marketing",
  "Social Media Copywriting",
  "Social Listening",
  "Crisis Management",
  "Social Media Campaigns",
  "Audience Growth Strategies",
  "Social Media Tools (Hootsuite, Buffer)",
  "Engagement Tactics",
  "A/B Testing",
  "Trend Spotting",
  "Brand Voice Development",
  "Social Media Audits",
];

// Data Analyst Skills
export const DATA_ANALYST_SKILLS = [
  "SQL",
  "Excel/Google Sheets",
  "Python",
  "R",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "Data Cleaning",
  "Data Transformation",
  "Statistical Analysis",
  "Predictive Analytics",
  "Data Modeling",
  "Database Management",
  "ETL Processes",
  "Business Intelligence",
  "A/B Testing",
  "Dashboard Creation",
  "Data Mining",
  "Reporting",
  "Data Storytelling",
  "Google Analytics",
  "Data Quality Assessment",
  "Pandas",
  "NumPy",
  "Regression Analysis",
];

// Game Developer Skills
export const GAME_DEVELOPER_SKILLS = [
  "Unity",
  "Unreal Engine",
  "C#",
  "C++",
  "3D Modeling",
  "2D Art",
  "Game Design",
  "Level Design",
  "Animation",
  "Physics Programming",
  "AI Programming",
  "Game UI Design",
  "Multiplayer Programming",
  "Sound Design",
  "Version Control",
  "Performance Optimization",
  "Mobile Game Development",
  "WebGL",
  "Game Monetization",
  "Game Testing",
  "Shader Programming",
  "Procedural Generation",
  "Game Mechanics",
  "Character Design",
  "Cross-Platform Development",
];

// All skills combined
export const ALL_SKILLS = {
  "wordpress-designer": WORDPRESS_DESIGNER_SKILLS,
  "frontend-developer": FRONTEND_DEVELOPER_SKILLS,
  "backend-developer": BACKEND_DEVELOPER_SKILLS,
  "fullstack-developer": FULLSTACK_DEVELOPER_SKILLS,
  "ui-ux-designer": UI_UX_DESIGNER_SKILLS,
  "mobile-app-developer": MOBILE_APP_DEVELOPER_SKILLS,
  "shopify-developer": SHOPIFY_DEVELOPER_SKILLS,
  "web-scraping-specialist": WEB_SCRAPING_SPECIALIST_SKILLS,
  "devops-engineer": DEVOPS_ENGINEER_SKILLS,
  "ai-ml-developer": AI_ML_DEVELOPER_SKILLS,
  "blockchain-developer": BLOCKCHAIN_DEVELOPER_SKILLS,
  "content-writer": CONTENT_WRITER_SKILLS,
  "seo-specialist": SEO_SPECIALIST_SKILLS,
  "social-media-manager": SOCIAL_MEDIA_MANAGER_SKILLS,
  "data-analyst": DATA_ANALYST_SKILLS,
  "game-developer": GAME_DEVELOPER_SKILLS,
};

export const AVAILABLE_PLATFORMS = [
  {
    name: "upwork",
    urlStructure: "https://www.upwork.com/nx/proposals/job/~[jobId]/apply/",
    coverLetterSelector:
      "div.air3-textarea textarea.air3-textarea.inner-textarea",
  },
  {
    name: "freelancer",
    urlStructure: "https://www.freelancer.com/projects/[jobId]/apply/",
    coverLetterSelector: "textarea#projectDescription",
  },
  {
    name: "fiverr",
    urlStructure: "https://www.fiverr.com/jobs/[jobId]/apply",
    coverLetterSelector: "textarea.job-application-textarea",
  },
  // Add more platforms as needed
];
